### PR TITLE
Using functools wraps on inner function

### PR DESCRIPTION
**Pull request by eduardomourar**
This fixes the same issues from PR #51 , but it also works for python 2.7.

I run into problems when trying to document the code that contained `@lambda_handler` and it was not possible because the wrapper function was not marked as decorator.

### CODE REVIEW

**Comment by sloev** [comment]
Prospector is being stupid here. I will fix on monday. 

If you dont wanna wait : read up on 

# pylint: disable=import-error

Context: https://stackoverflow.com/questions/9602811/how-to-tell-pylint-to-ignore-certain-imports

Or consider:

Try:
Import py27 specific
Except importerror:
Import py3+ specific

**Comment by sloev** [comment]
Btw @eduardomourar 
If you have recent knowledge about using lambdarest with aws api-gateway, maybe you could help with this issue:

https://github.com/trustpilot/python-lambdarest/issues/38

As i personally haven't used the lib for two years 😅

**Comment by eduardomourar** [comment]
@sloev, I cannot promise it, but I will try to look into #38.

**Comment by sloev** [comment]
Dont need to promise anything 😅
Do you need your pr release urgently? Else i'll wait until monday

**Comment by eduardomourar** [comment]
We can wait until Monday without a problem. Thanks!

**Comment by sloev** [comment]
@eduardomourar version 6.0.0 is released featuring your patch

**Pull request merged**
